version: "3"

vars:
  BINARY_NAME: digital-wallet-api
  MAIN_PATH: ./cmd/api/main.go

tasks:
  tidy:
    desc: Run code formatting and linting
    cmds:
      - go fmt ./...
      - go tidy -v
  dev:
    desc: Start the development server
    cmds:
      - go run {{.MAIN_PATH}}

  build:
    desc: Build the application
    cmds:
      - go build -o bin/{{.BINARY_NAME}} {{.MAIN_PATH}}

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...
